### ISSUE TITLE
Helics + Matlab + GridlabD Co-Simulation Environment

### ISSUE THREAD

**Issue by StormsHalted** [GMLC-TDC/matHELICS#1]
Afternoon Everyone,

I am developing a co-simulation based on Helics + GridlabD + Matlab.

I already have a **GridlabD + Helics** integration set-up running on a Ubuntu 20.4 machine.

**Helics Version:**
2.8.0 (2021-09-17)

**Gridlab-D Version:**
GridLAB-D 4.3.0-18923 (Navajo [107009aa:HEAD]) 64-bit LINUX RELEASE

Now I did a standalone install of **Matlab version:**
R2022a Update 2.

Now my question is how I can integrate my existing Helics build with Matlab? Do I have to execute the procedure listed on below link, As it is or their will be some modifications, as I do not want to interfere with the older Helics + Gridlabd integration:

[This Link](https://docs.helics.org/en/helics2/introduction/matlab.html)

**On a side note**, when I execute the make step of the swig install, I get the following error:

~/swig$ make
make[1]: Entering directory '/home/ali/swig/Source'
/bin/bash ../Tools/config/ylwrap CParse/parser.y y.tab.c CParse/parser.c y.tab.h `echo CParse/parser.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output CParse/parser.output -- yacc -d 
../Tools/config/ylwrap: line 176: yacc: command not found
make[1]: *** [Makefile:1001: CParse/parser.c] Error 127
make[1]: Leaving directory '/home/ali/swig/Source'
make: *** [Makefile:36: source] Error 2

Any help would be very appreciated.

**Comment by nightlark** [comment]
For the error building swig, it says the yacc command wasn’t found. I’d try
installing the yacc package for your Linux distro; I believe the bison
(modern replacement for yacc) package will also install a yacc command that
makes it run in a yacc-compatible mode.

I’m guessing the new matHELICS interface will not work with HELICS 2, so
the old swig generated interface will be the only option. At some point I’d
recommend updating to HELICS 3, since 2 is more or less end of life/support.

**Comment by StormsHalted** [comment]
Alright yes! this makes me get past the make step and complete the swig installation:

How can you possibly ensure that Matlab and Swig are in the same PATH?

I get the error on next step:

ali@WSU-UIAssist-Ali:~/swig$ swig -I../src/helics/shared_api_library -outdir ./matlab -matlab ./helicsMATLAB.i
mv helics_wrap.cxx matlab/helicsMEX.cxx
swig error : Unrecognized option -matlab
Use 'swig -help' for available options.
mv: cannot stat 'helics_wrap.cxx': No such file or directory

**Comment by nightlark** [comment]
Matlab and swig don’t need to be on the same path — running swig to
generate files doesn’t actually run matlab (or even require matlab to be
installed). The `./matlab` is the argument to the `-outdir` option, which
is telling swig to put the generated files in a subfolder named matlab
(feel free to change the output folder name to make it less confusing).

`-matlab` is the option that tells swig to generate code files compatible
with matlab (swig has other options to make it output code for other
languages like Java, Python, etc).

The main version of swig doesn’t support matlab — since it says the
`-matlab` option was not recognized, I’d say make sure you built and
installed swig from https://github.com/jaeandersson/swig and not the main
swig repository. If you did, check to make sure you are actually running
the copy of swig you compiled and not a different version of swig installed
somewhere else on your computer. `which swig` Can give you the full path to
where the `swig` command you ran is actually located, and `swig -version`
will print out the version number — I think the swig fork with matlab
support should say a version number around 3.0.10 or 3.0.12; if it says
4.something the copy you ran is definitely not the matlab fork version.

**Comment by StormsHalted** [comment]
Unfortunately, My swig version came to:

```
ali@WSU-UIAssist-Ali:~$ swig -version

SWIG Version 4.0.2

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre
```
I wish my life was easier ....................

So, I download the old 3.08 swig tarball.gz, then I run it through ./configure, it gives an error that PCRE was not found and throws the following instruction:

`        Cannot find pcre-config script from PCRE (Perl Compatible Regular Expressions)
        library package. This dependency is needed for configure to complete,
        Either:
        - Install the PCRE developer package on your system (preferred approach).
        - Download the PCRE source tarball, build and install on your system
          as you would for any package built from source distribution.
        - Use the Tools/pcre-build.sh script to build PCRE just for SWIG to statically
          link against. Run 'Tools/pcre-build.sh --help' for instructions.
          (quite easy and does not require privileges to install PCRE on your system)
        - Use configure --without-pcre to disable regular expressions support in SWIG
          (not recommended).
`

Then I download PCRE 2.10.40 from here:

https://github.com/PCRE2Project/pcre2/releases

extract the tarball and then run ./configure. PCRE installs successfully.

Now I can't seem to execute step 3.

When I go inside the tools folder their is a file pcre-build.sh.

I copy it outside the tools folder and then try to run it from terminal. Doesn't work.

I can't seem to interpret this step correctly: 

`- Run this script in the same directory that you intend to configure and build SWIG in.`

Thanks for your support though ........ This is complicated.

**Comment by nightlark** [comment]
> So, I download the old 3.08 swig tarball.gz, then I run it through ./configure, it gives an error that PCRE was not found and throws the following instruction:

Since you're trying to work with matlab, make sure you are using a tarball from: https://github.com/jaeandersson/swig (the main swig repository has never had support for matlab). I wouldn't bother with tags since those might not have the matlab code added in, instead fetch a copy of the latest version of the `matlab` branch source code either using a git clone or downloading the zip file https://github.com/jaeandersson/swig/archive/refs/heads/matlab.zip from GitHub.

> Cannot find pcre-config script from PCRE (Perl Compatible Regular Expressions) library package. This dependency is needed for configure to complete, Either:
> - Install the PCRE developer package on your system (preferred approach).
> - Download the PCRE source tarball, build and install on your system as you would for any package built from source distribution.
> - Use the Tools/pcre-build.sh script to build PCRE just for SWIG to statically link against. Run 'Tools/pcre-build.sh --help' for instructions. (quite easy and does not require privileges to install PCRE on your system) - Use configure --without-pcre to disable regular expressions support in SWIG (not recommended).
> 
> Then I download PCRE 2.10.40 from here:
> 
> https://github.com/PCRE2Project/pcre2/releases
> 
> extract the tarball and then run ./configure. PCRE installs successfully.

Generally, `./configure` is just the first step that sets up the build system; usually afterwards you need to run `make install` to actually compile and install the code. I'd also recommend setting an install prefix other than the default system location when running configure to avoid interfering with the newer copy of swig you have installed: e.g. `./configure --prefix=$SWIG_SOURCE_DIR/pcre/pcre-swig-install` (replace `$SWIG_SOURCE_DIR` with the path to the copy of the swig source code -- as in the folder containing the README file for swig).

> Now I can't seem to execute step 3.

The three things listed are separate options, so there shouldn't be a step 3; since you choose option 2 (`Download the PCRE source tarball, build and install on your system as you would for any package built from source distribution`), you can ignore the bullet points above and below that.

The following step would be compiling swig and if you got the install prefix set correctly then it should automatically detect the copy of PCRE you installed; otherwise, run the swig `./configure` step with the `--with-pcre=$PATH_TO_PCRE_INSTALL` to tell it exactly where PCRE was installed to.

> When I go inside the tools folder their is a file pcre-build.sh.
> 
> I copy it outside the tools folder and then try to run it from terminal. Doesn't work.
> 
> I can't seem to interpret this step correctly:
> 
> `- Run this script in the same directory that you intend to configure and build SWIG in.`

If you're following option 2, you can ignore this 3rd option. Though what that line means is if you want to build in a folder named `arandomswigbuildfolder` then you change directory to `arandomswigbuildfolder` in your terminal, then DO NOT copy the script; instead, run the script while you are in the `arandomswigbuildfolder` directory by giving the full path to the `pcre-build.sh` script.

(If you have root then install the pcre-devel package using the package manager on your system as it mentions for option 1 and you should be able to skip the other two methods of getting PCRE).

**Comment by StormsHalted** [comment]
Alright!

I get some success in making the make install step run correctly. It goes on to print that libraries have been installed in /usr/local/lib. Basically the script runs without errors, thouigh I had to use root.

Now, as you are discarding step 3, I only need to run 2.

So, my swig path is:
`/home/ali/swig-3.0.8`

My new pcre install path is:
`/home/ali/swig-3.0.8/pcre2-10.40`.

I still get the same pcre not found error, as I execute:
`./configure --with-pcre=/home/ali/swig-3.0.8/pcre2-10.40`

Is it because I used pcre 2 instead of just pcre? What could be going wrong now?

**Comment by nightlark** [comment]
> My new pcre install path is: `/home/ali/swig-3.0.8/pcre2-10.40`.

Based on what you said, you installed PCRE into `/usr/local/lib`, not `/home/Ali/swig-3.0.8/pcre2-10.40`. If you meant to install it into a different path, you need to *go into the pcre source code folder and re-run* `./configure --prefix=<path to install pcre into>`, then *re-run make install* for pcre.

> I still get the same pcre not found error, as I execute: `./configure --with-pcre=/home/ali/swig-3.0.8/pcre2-10.40`

Given that PCRE was installed into `/usr/local/lib`, you would not want to use the `--with-pcre` arg and instead just let `./configure` detect the system install.

> Is it because I used pcre 2 instead of just pcre? What could be going wrong now?

I have no idea, but I wouldn't be surprised. Try asking on the swig mailing list/GitHub -- though since 3.x swig versions are so old, it might be hard to get support.

> Update:
> 
> I also downloaded the swig-matlab zip, unfortunately could not locate a configure file in the unzipped folder.

See https://github.com/GMLC-TDC/helics-buildenv/blob/main/interface-gen/Dockerfile#L10-L12 for an example of the commands that you need to run in order to build and install the swig-matab zip file code. Specifically, it looks like they have a shell script called autogen.sh that probably runs autoconf and stuff.

Where did you get the copy of swig-3.0.8 from? What is the full link to the download you are using?

**Comment by StormsHalted** [comment]
I downloaded the previous version of swig from:

https://cytranet.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz

But now, I download the link mentioned by you again. Also I download the older version of PCRE and `make install` it.

Next I run, your version of swig and follow the instructions in root:

after the configure step I get:

`The SWIG test-suite and examples are configured for the following languages:
d matlab perl5 python `

after the -J4 and make step I get: (I do them one at a time) without cd swig.

`make[1]: Leaving directory '/root/swig/CCache'
Installation complete
`
Here, I close the terminal and get out of root.

So I believe It was the new version of PCRE that was causing trouble with the SWIG. Now I should move to the next step:

I have to enable `BUILD_MATLAB_INTERFACE` in my existing Helics 2.8. 

Existing tutorials posted on website show steps that will build a new Helics, so I am not sure, how to make this work in an existing install.

I can then follow the tutorial from `mex -setup` step.

**Comment by nightlark** [comment]
Sorry, I missed this response -- though it sounds like you got something working.

> Existing tutorials posted on website show steps that will build a new Helics, so I am not sure, how to make this work in an existing install.

A copy of the HELICS source code is still needed, but you can use the `interfaces/matlab` subfolder as a standalone CMake project -- it has a CMakeLists.txt file that is perfectly happy to be used as the source folder when running the CMake. Look at the CMakeLists.txt file for the options available: https://github.com/GMLC-TDC/HELICS/blob/v2.8.1/interfaces/matlab/CMakeLists.txt

The general idea for using the matlab interfaces folder for a "standalone" build with an existing HELICS install is you will configure a CMake option to point it to the folder that the existing copy of HELICS is installed to (_not_ the HELICS source code folder that contains the `interfaces/matlab` folder), and make sure it finds the copy of SWIG that you compiled.

**Comment by StormsHalted** [comment]
Evening,

I decided to rebuild Helics 2 from scratch, considering my inability to comprehend the other alternative.

While executing the helics set-up with `DBUILD_MATLAB_INTERFACE=ON`. I get the following status messages ...

`-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.9.so (found suitable version "3.9.7", minimum required is "3") 
-- Building without swig
-- Found Matlab: /usr/local/MATLAB/R2022a/extern/include (found version "9.12") found components: MAIN_PROGRAM 
-- Building MATLAB
-- Building without swig
-- Extra /home/ali/cosim2_env/sources/helicsv2.8.0/interfaces/matlab/extra/helicsInputSetDefault.m;/home/ali/cosim2_env/sources/helicsv2.8.0/interfaces/matlab/extra/helicsPublicationPublish.m
-- Git hooks disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ali/cosim2_env/sources/helicsv2.8.0/build`

Apparently it shows that, it found matlab, but I am not sure if it is able to detect SWIG.

Next, I see that the mex setup also completes successfully.

Unfortunatly though, as I run the `helicsStartup()` in linux command line matlab, I get this error message:

`>> helicsStartup
Loading HELICS (from /home/ali/cosim2_env/matlab)...
Warning: The library name is not a valid name.
The library will be named "libhelicsSharedLib0x2Eso0x2E20x2E8". 
> In loadlibrary
In helicsStartup (line 56) 
Error using loadlibrary
Could not find file libhelicsSharedLib.so.2.8.

Error in loadlibrary

Error in helicsStartup (line 56)
        loadlibrary(GetFullPath(fullfile(helicsLibPath, libraryName)));
`
So my Helics + Matlab link is still not working.

**Comment by StormsHalted** [comment]
Looks like I should start a new thread for it in GMLC -TDC as this is closed.

[https://github.com/GMLC-TDC/HELICS/issues/2390]
